# Generated by Django 4.1.1 on 2024-05-16 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentence',
            name='level',
        ),
    ]
