# Generated by Django 4.1.1 on 2024-05-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0002_remove_sentence_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='original',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='translation',
            field=models.CharField(max_length=500),
        ),
    ]
