# Generated by Django 4.1.1 on 2024-05-16 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sentences', '0003_alter_sentence_original_alter_sentence_translation'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentence',
            name='level',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
