# Generated by Django 5.1.1 on 2024-09-13 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(max_length=500)),
                ('translation', models.TextField(max_length=500)),
                ('level', models.CharField(max_length=1)),
            ],
        ),
    ]
